# 기본(default) 룰이 아닌 룰들을 활성화
opt_in_rules:
    - sorted_imports
    
line_length:
  warning: 250
  error: 300

function_body_length:
    warning: 100
    error: 150

disabled_rules:
  - force_cast
  - blanket_disable_command
  
function_parameter_count:
  warning: 5
  error: 10

identifier_name:
  min_length: 2
  max_length: 40
  
type_name:
  min_length: 3
  max_length: 60
